# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 730a020e0a4504d6dc0e3d1a98a9c1a3d7ff068e797e8067b3fbf2583716391b4613274e3cdbc04082f97681ac170cc30b1474472e33c6eb061a29b63eb00cec

test:
  secret_key_base: 68dc9e301f3d51e0ef12a166020838050f47b69bc7f21fafd6508392089f2a922fbc006440ecc008b4379327a51a8f156ef16f57dab3f62de8dc5cb5bacc33b6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
